# Generated by Django 4.1.2 on 2022-11-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_treeinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='treeinfo',
            name='more_info',
            field=models.TextField(default='', max_length=255, verbose_name='Additional information'),
        ),
    ]
