# Generated by Django 4.1.2 on 2022-11-13 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_useraddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treeinfo',
            old_name='created_by',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='created_by',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='useraddress',
            old_name='created_by',
            new_name='username',
        ),
    ]
