# Generated by Django 4.1.2 on 2022-11-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_created_by_treeinfo_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treeinfo',
            name='files',
            field=models.FileField(null=True, upload_to='', verbose_name='Evidence'),
        ),
    ]
