# Generated by Django 4.1.2 on 2022-12-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_treeinfo_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='county',
            field=models.CharField(default='unknown', max_length=50, verbose_name='County'),
        ),
        migrations.AddField(
            model_name='user',
            name='full_address',
            field=models.CharField(default='unknown', max_length=255, verbose_name='Full Address'),
        ),
        migrations.AddField(
            model_name='user',
            name='town',
            field=models.CharField(default='unknown', max_length=50, verbose_name='Town'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='unknown', max_length=255, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='unknown', max_length=255, verbose_name='Last name'),
        ),
        migrations.DeleteModel(
            name='UserAddress',
        ),
    ]
