# Generated by Django 4.1.2 on 2022-12-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_user_full_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Your Name')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('email', models.CharField(max_length=100, verbose_name='Your Email')),
                ('subject', models.CharField(max_length=100, verbose_name='Subject')),
                ('message', models.TextField(max_length=255, verbose_name='Message')),
            ],
        ),
    ]
