# Generated by Django 4.1.2 on 2023-01-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treeinfo',
            name='more_info',
            field=models.TextField(default='No additional information given', max_length=255, verbose_name='Additional information'),
        ),
    ]
