# Generated by Django 4.1.2 on 2023-01-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_treeinfo_more_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treeinfo',
            name='more_info',
            field=models.TextField(default='No additional information given', max_length=255, null=True, verbose_name='Additional information'),
        ),
    ]
