# Generated by Django 4.1.2 on 2023-01-08 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='status',
        ),
    ]
