# Generated by Django 4.1.2 on 2023-01-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_notifications_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='status',
            field=models.CharField(choices=[('unread', 'unread'), ('read', 'read')], default=('unread', 'unread'), max_length=255, verbose_name='Status'),
        ),
    ]
