# Generated by Django 4.1.2 on 2023-01-08 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_notifications_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='status',
            field=models.CharField(choices=[('unread', 'unread'), ('read', 'read')], default='unread', max_length=255, verbose_name='Status'),
        ),
    ]
