# Generated by Django 4.1.2 on 2023-01-08 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_notifications_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='username',
            field=models.CharField(max_length=255, verbose_name='Username'),
        ),
    ]
