# Generated by Django 4.1.2 on 2023-01-09 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_notifications_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='date',
            field=models.CharField(default='2023-01-09', max_length=150, verbose_name='Time sent'),
        ),
    ]
