# Generated by Django 4.1.2 on 2023-01-09 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_notifications_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='date',
        ),
        migrations.AddField(
            model_name='notifications',
            name='time_sent',
            field=models.CharField(default='not set', max_length=150, verbose_name='Time sent'),
            preserve_default=False,
        ),
    ]
