# Generated by Django 4.1.2 on 2023-01-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_remove_notifications_date_notifications_time_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='when',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
