# Generated by Django 4.1.2 on 2023-01-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_notifications_when'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='when',
            field=models.DateTimeField(auto_now_add=True, default='2023-01-11T18:15:21.728141Z'),
            preserve_default=False,
        ),
    ]
