# Generated by Django 4.1.2 on 2023-01-11 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_notifications_when'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='when',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 11, 18, 40, 44, 165384, tzinfo=datetime.timezone.utc)),
        ),
    ]
