# Generated by Django 4.1.2 on 2023-01-11 20:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_notifications_when'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='when',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 11, 20, 39, 0, 770841, tzinfo=datetime.timezone.utc)),
        ),
    ]
