# Generated by Django 4.1.2 on 2023-01-11 20:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_notifications_when'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='when',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
