# Generated by Django 4.1.2 on 2022-11-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Community name')),
                ('created_by', models.CharField(max_length=255, verbose_name='Created by')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('community_id', models.CharField(max_length=100, verbose_name='Community ID')),
                ('verif_code', models.CharField(max_length=255, verbose_name='Verification code')),
            ],
        ),
    ]
