# Generated by Django 4.1.2 on 2022-12-02 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='community',
            unique_together=set(),
        ),
    ]
