# Generated by Django 4.1.2 on 2022-11-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_id', models.CharField(max_length=255, verbose_name='Community ID')),
                ('activity_name', models.CharField(max_length=255, verbose_name='Activity name')),
                ('activity_details', models.TextField(blank=True, verbose_name='Activity details')),
                ('activity_date', models.DateField(auto_now_add=True, verbose_name='Activity date')),
            ],
        ),
        migrations.CreateModel(
            name='CommunityMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, verbose_name='Member username')),
                ('member_to', models.CharField(max_length=255, verbose_name='Member to')),
                ('joining_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
