# Generated by Django 4.1.2 on 2022-11-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_communityactivities_communitymembers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitymembers',
            name='joining_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
