# Generated by Django 4.1.2 on 2022-11-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_alter_communitymembers_joining_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='region',
            field=models.CharField(default='Kenya', max_length=30, verbose_name='Region'),
        ),
    ]
