# Generated by Django 4.1.2 on 2023-01-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_alter_community_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='verif_code',
            field=models.CharField(default='JU9HF0IY6', max_length=255, unique=True, verbose_name='Verification code'),
        ),
    ]
