# Generated by Django 4.1.2 on 2023-01-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_alter_community_verif_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='verif_code',
            field=models.CharField(default='KPO3TY0H4', max_length=255, verbose_name='Verification code'),
        ),
    ]
