# Generated by Django 4.1.2 on 2022-11-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0005_alter_community_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Community name'),
        ),
        migrations.AlterUniqueTogether(
            name='community',
            unique_together={('name', 'region')},
        ),
    ]
