# Generated by Django 4.1.2 on 2023-01-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0006_alter_community_verif_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='verif_code',
            field=models.CharField(default='MFCDQJM9', max_length=255, unique=True, verbose_name='Verification code'),
        ),
    ]
