# Generated by Django 4.1.2 on 2023-01-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0009_alter_community_verif_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='verif_code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Verification code'),
        ),
    ]
