# Generated by Django 4.1.2 on 2023-01-06 15:25

from django.db import migrations, models
from ..models import Community, CommunityMembers

def setDefaults():
    codes = CommunityMembers.objects.values_list('member_to')
    for i in codes:
        comm = Community.objects.filter(verif_code=i).values_list('name')
        return comm
    

def communitymem(apps, schema_editor):
    CommunityMembers = apps.get_model('communities', 'CommunityMembers')
    db_alias = schema_editor.connection.alias
    
    codes = CommunityMembers.objects.values_list('member_to')
    for i in codes:
        comm = Community.objects.filter(verif_code=i).values_list('name')
        CommunityMembers.objects.using(db_alias).create(
            community=comm
        )

class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0013_alter_community_verif_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='verif_code',
            field=models.CharField(max_length=9, unique=True, verbose_name='Verification code'),
        ),
        migrations.RunPython(communitymem),
    ]
