# Generated by Django 4.1.2 on 2023-01-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0014_alter_community_verif_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitymembers',
            name='community',
            field=models.CharField(default='undefined', max_length=255, verbose_name='Community'),
            preserve_default=False,
        ),
    ]
