# Generated by Django 4.1.2 on 2023-01-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0015_communitymembers_community'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='community',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='communitymembers',
            name='community',
            field=models.CharField(default='Unknown', max_length=255, verbose_name='Community'),
        ),
    ]
