# Generated by Django 4.1.2 on 2023-01-06 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0016_alter_community_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='community',
            unique_together={('name', 'region')},
        ),
    ]
