# Generated by Django 4.1.2 on 2023-01-07 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0017_alter_community_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitymembers',
            name='member_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.community'),
        ),
    ]
