# Generated by Django 4.1.2 on 2023-01-07 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0018_alter_communitymembers_member_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communitymembers',
            old_name='member_to',
            new_name='verif_code',
        ),
        migrations.AlterUniqueTogether(
            name='communitymembers',
            unique_together={('user', 'verif_code')},
        ),
    ]
