# Generated by Django 4.1.2 on 2023-01-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0019_rename_member_to_communitymembers_verif_code_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='communitymembers',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='communitymembers',
            name='member_to',
            field=models.CharField(default='undefined', max_length=255, verbose_name='Member to'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='communitymembers',
            unique_together={('user', 'member_to')},
        ),
        migrations.RemoveField(
            model_name='communitymembers',
            name='verif_code',
        ),
    ]
