# Generated by Django 4.1.2 on 2023-01-07 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0021_community_members_no'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='communitymembers',
            unique_together={('user', 'community')},
        ),
    ]
